apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: hellowd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellowd
  template:
    metadata:
      labels:
        app: hellowd
    spec:
      containers:
      - name: hello-container
        image: ${ACR_REGISTRY}/${ACR_REPOSITORY}:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    matchLabels:
      app: hellowd
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
